# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 0.35%  # Current baseline coverage
        threshold: 5%  # Allow 5% decrease before failing
    patch:
      default:
        target: 50%  # New code should have at least 50% coverage

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "src/bin/**/*"
  - "**/*_test.rs"
  - "**/*test*.rs"
